### ISSUE TITLE
Possible freeze on XF86AudioPlay

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#167]
@PMunch mentioned this issue briefly in IRC.

Would like more info if possible, will manually test later.

**Comment by PMunch** [comment]
I wouldn't worry about this. I tested it in i3 and it has the exact same issue. I tried to record thing with `xev` but it doesn't actually output the `XF86AudioPlay` button but rather some keyboard remap events (probably to use a different USB code page) and then it simply just hangs i3 (but not `xev` curiously). I can get i3 to unfreeze by sending it a SIGCONT, at which point it runs the action associated with the button. It also starts working normally after that, allowing me to hit the button and have the action running without i3 freezing. SIGCONT (and the associated SIGSTOP) is used for job control, it's the same thing that happens when you hit CTRL+Z in a terminal that suspends the current process and drops you back to the shell, and then you can use `fg` to start the process again and bring it to the front of the terminal. Not quite sure how i3 ends up being suspended though.. There is an issue [here](https://github.com/i3/i3/issues/2539) for i3 if you want to try and figure it out.

**Comment by PMunch** [comment]
I tried the same SIGCONT thing with nimdow and it didn't work.

**Comment by avahe-kellenberger** [comment]
Interesting, thanks for the info. What gets sent instead of XF86AudioPlay?

**Comment by PMunch** [comment]
Slight correction, it was just `xev` that didn't get the event because i3 already had handled it. If I remove the keybinding in the i3 configuration it shows the event.

**Comment by avahe-kellenberger** [comment]
@PMunch Is this the freezing you mentioned in the channel today? I want to prevent this from happening, hoping to get more info so you won't have any more trouble.

**Comment by PMunch** [comment]
Well I did hit a button when it happened, but it wasn't any of the audio ones. I think there might be some obscure event that isn't handled which just freezes everything, but I can't really pinpoint what it would be..

**Comment by avahe-kellenberger** [comment]
I'm hoping we can narrow it down - I don't have bindings to any events like `XF86AudioPlay`, would be useful if we could iterate through yours to find the problem

**Comment by PMunch** [comment]
Just got a call via bluetooth which froze the desktop. So it might be related to an interaction between the bluetooth headset and Nimdow. Not quite sure how that would happen, my best guess is some event queue issue.

**Comment by avahe-kellenberger** [comment]
PMunch found that the headset is being registered as a "keyboard", and might be triggering `XF86AudioPlay` or a similar event.

dwm handles `MappingNotify` events, may be related:

```c
void
mappingnotify(XEvent *e)
{
  XMappingEvent *ev = &e->xmapping;

  XRefreshKeyboardMapping(ev);
  if (ev->request == MappingKeyboard)
    grabkeys();
}
```

Xlib docs:

```
MappingNotify Events
  The X server reports MappingNotify events to all clients. There is no mechanism to
express disinterest in this event. The X server generates this event type whenever
a client application successfully calls:
• XSetModifierMapping to indicate which KeyCodes are to be used as modifiers
• XChangeKeyboardMapping to change the keyboard mapping
• XSetPointerMapping to set the pointer mapping
```

**Comment by PMunch** [comment]
After having probed into this further with the help from `#archlinux` it turns out it was a simple DBus issue. I have been able to resolve the issue now. Sorry for the confusion.
